---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: "akhq"
  replicas: 1
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: cp-registry-container
          image: tchiotludo/akhq:0.15.0
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    docker-kafka-server:
                      properties:
                        bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
                      schema-registry:
                        url: "http://schema-registry-service:8081"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akhq-service
  namespace: kafka
spec:
  ports:
    - port: 8080
  clusterIP: None
  selector:
    app: akhq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akhq-ingress
  namespace: kafka
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: akhq.cluster.local
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: akhq-service
                port:
                  number: 8080