apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: tracking-energy-rawevent
  namespace: kafka
spec:
  config:
    cleanup.policy: delete
    compression.type: producer
  partitions: 8
  replicas: 1
  topicName: tracking.energy.rawevent