apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: maning-kafka-db-postgresql-service
  name: maning-kafka-db-postgresql-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: tcp-external
      nodePort: 30032
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: manning-kafka-db
    app.kubernetes.io/name: postgresql